version: "3.9"

volumes:
  mysql_data:

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=']
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '33060:3306'

  notes:
    build: .
    env_file:
      - '.env.docker'
    command: >
      gunicorn -b 0.0.0.0:5000
      -w 2
      --access-logfile -
      --reload
      app:app
    ports:
      - "5000"
    expose:
      - '5000'
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - nginx
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_notes
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - '5001:80'
    restart: on-failure
